import { CandidateAnalysis, LatexResumePackage, ResumeData, ResumeExperience, ResumeProject } from '../src/types';

/**
 * Escapes special LaTeX characters to prevent syntax compilation errors
 */
export function escapeLatex(str: string): string {
  if (!str) return '';
  return str
    .replace(/\\/g, '\\textbackslash{}')
    .replace(/&/g, '\\&')
    .replace(/%/g, '\\%')
    .replace(/\$/g, '\\$')
    .replace(/#/g, '\\#')
    .replace(/_/g, '\\_')
    .replace(/{/g, '\\{')
    .replace(/}/g, '\\}')
    .replace(/~/g, '\\textasciitilde{}')
    .replace(/\^/g, '\\textasciicircum{}');
}

/**
 * Generates an ATS-compliant, single-column LaTeX source code (Jake's Resume / Harvard Standard)
 */
export function buildLatexResumeDocument(data: ResumeData): string {
  const name = escapeLatex(data.fullName || 'Candidate Name');
  const email = escapeLatex(data.email || 'candidate@example.com');
  const phone = escapeLatex(data.phone || '+1 (555) 019-2834');
  const location = escapeLatex(data.location || 'San Francisco, CA');
  const linkedin = data.links.linkedin ? escapeLatex(data.links.linkedin) : 'linkedin.com/in/profile';
  const github = data.links.github ? escapeLatex(data.links.github) : 'github.com/profile';
  const portfolio = data.links.portfolio ? escapeLatex(data.links.portfolio) : '';

  // Format Experience Items
  const experienceSections = data.experience
    .map((exp) => {
      const role = escapeLatex(exp.role);
      const company = escapeLatex(exp.company);
      const loc = escapeLatex(exp.location);
      const duration = escapeLatex(exp.duration);
      const bulletItems = exp.bullets
        .map((b) => `      \\resumeItem{${escapeLatex(b)}}`)
        .join('\n');

      return `    \\resumeSubheading
      {${role}}{${duration}}
      {${company}}{${loc}}
      \\resumeItemListStart
${bulletItems}
      \\resumeItemListEnd`;
    })
    .join('\n\n');

  // Format Project Items
  const projectSections = data.projects
    .map((proj) => {
      const title = escapeLatex(proj.title);
      const techs = escapeLatex(proj.technologies);
      const bulletItems = proj.bullets
        .map((b) => `      \\resumeItem{${escapeLatex(b)}}`)
        .join('\n');

      return `    \\resumeProjectHeading
      {\\textbf{${title}} $|$ \\emph{${techs}}}{}
      \\resumeItemListStart
${bulletItems}
      \\resumeItemListEnd`;
    })
    .join('\n\n');

  // Format Skills
  const languagesStr = escapeLatex(data.skills.languages.join(', '));
  const frameworksStr = escapeLatex(data.skills.frameworks.join(', '));
  const devToolsStr = escapeLatex(data.skills.developerTools.join(', '));
  const librariesStr = escapeLatex(data.skills.librariesOrDatabases.join(', '));

  // Format Education
  const educationSections = data.education
    .map((edu) => {
      const inst = escapeLatex(edu.institution);
      const deg = escapeLatex(edu.degree);
      const loc = escapeLatex(edu.location);
      const duration = escapeLatex(edu.duration);
      const details = edu.details ? `\\resumeItem{${escapeLatex(edu.details)}}` : '';

      return `    \\resumeSubheading
      {${inst}}{${loc}}
      {${deg}}{${duration}}
      ${details ? `\\resumeItemListStart\n      ${details}\n      \\resumeItemListEnd` : ''}`;
    })
    .join('\n\n');

  return `%-------------------------
% Auto-Generated by OmniApply AI
% ATS-Optimized Single-Column Harvard / Jake's Resume Template
%------------------------

\\documentclass[letterpaper,11pt]{article}

\\usepackage{latexsym}
\\usepackage[empty]{fullpage}
\\usepackage{titlesec}
\\usepackage{marvosym}
\\usepackage[usenames,dvipsnames]{color}
\\usepackage{verbatim}
\\usepackage{enumitem}
\\usepackage[hidelinks]{hyperref}
\\usepackage{fancyhdr}
\\usepackage[english]{babel}
\\usepackage{tabularx}
\\usepackage{fontawesome5}
\\input{glyphtounicode}

% Ensure that generate pdf is machine readable/ATS parsable
\\pdfgentounicode=1

\\pagestyle{fancy}
\\fancyhf{}
\\fancyfoot{}
\\renewcommand{\\headrulewidth}{0pt}
\\renewcommand{\\footrulewidth}{0pt}

% Adjust margins
\\addtolength{\\oddsidemargin}{-0.5in}
\\addtolength{\\evensidemargin}{-0.5in}
\\addtolength{\\textwidth}{1in}
\\addtolength{\\topmargin}{-.5in}
\\addtolength{\\textheight}{1.0in}

\\urlstyle{same}

\\raggedbottom
\\raggedright
\\setlength{\\tabcolsep}{0in}

% Sections formatting
\\titleformat{\\section}{
  \\vspace{-4pt}\\scshape\\raggedright\\large
}{}{0em}{}[\\color{black}\\titlerule \\vspace{-5pt}]

% Custom commands
\\newcommand{\\resumeItem}[1]{
  \\item\\small{
    {#1 \\vspace{-2pt}}
  }
}

\\newcommand{\\resumeSubheading}[4]{
  \\vspace{-2pt}\\item
    \\begin{tabular*}{0.97\\textwidth}[t]{l@{\\extracolsep{\\fill}}r}
      \\textbf{#1} & #2 \\\\
      \\textit{\\small#3} & \\textit{\\small #4} \\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\newcommand{\\resumeProjectHeading}[2]{
    \\item
    \\begin{tabular*}{0.97\\textwidth}{l@{\\extracolsep{\\fill}}r}
      \\small#1 & #2 \\\\
    \\end{tabular*}\\vspace{-7pt}
}

\\newcommand{\\resumeItemListStart}{\\begin{itemize}[leftmargin=0.15in, label={$\\bullet$}]}
\\newcommand{\\resumeItemListEnd}{\\end{itemize}\\vspace{-5pt}}

%-------------------------------------------
%%%%%%  RESUME STARTS HERE  %%%%%%%%%%%%%%%%%%%%%%%%%%%%

\\begin{document}

%----------HEADING----------
\\begin{center}
    \\textbf{\\Huge \\scshape ${name}} \\\\ \\vspace{1pt}
    \\small ${phone} $|$ \\href{mailto:${email}}{\\underline{${email}}} $|$ 
    \\href{https://${linkedin}}{\\underline{${linkedin}}} $|$
    \\href{https://${github}}{\\underline{${github}}}${portfolio ? ` $|$ \\href{https://${portfolio}}{\\underline{${portfolio}}}` : ''}
\\end{center}


%-----------EDUCATION-----------
\\section{Education}
  \\resumeSubHeadingListStart
${educationSections}
  \\resumeSubHeadingListEnd


%-----------TECHNICAL SKILLS-----------
\\section{Technical Skills}
 \\begin{itemize}[leftmargin=0.15in, label={}]
    \\small{\\item{
     \\textbf{Languages}{: ${languagesStr}} \\\\
     \\textbf{Frameworks \\& Runtimes}{: ${frameworksStr}} \\\\
     \\textbf{Databases \\& Cloud}{: ${librariesStr}} \\\\
     \\textbf{Developer Tools}{: ${devToolsStr}}
    }}
 \\end{itemize}


%-----------EXPERIENCE-----------
\\section{Professional Experience}
  \\resumeSubHeadingListStart

${experienceSections}

  \\resumeSubHeadingListEnd


%-----------PROJECTS-----------
\\section{Featured Engineering Projects}
    \\resumeSubHeadingListStart

${projectSections}

    \\resumeSubHeadingListEnd

%-------------------------------------------
\\end{document}
`;
}

/**
 * Builds a tailored structured resume package for a target role
 */
export function generateTailoredResumePackage(
  candidate: CandidateAnalysis,
  jobTitle: string,
  companyName: string,
  jobDescription: string
): LatexResumePackage {
  const jdLower = (jobDescription || '').toLowerCase();
  
  // Extract targeted ATS keywords from JD
  const keywordCandidates = [
    'TypeScript', 'React', 'Node.js', 'Python', 'Go', 'PostgreSQL', 'Redis',
    'Docker', 'Kubernetes', 'GraphQL', 'AWS', 'GCP', 'Kafka', 'System Design',
    'Microservices', 'CI/CD', 'REST APIs', 'TailwindCSS', 'Next.js', 'Distributed Systems'
  ];
  
  const atsKeywordsTargeted = keywordCandidates.filter((k) => 
    jdLower.includes(k.toLowerCase()) || 
    candidate.skillsMatrix.some((cat) => cat.skills.some((s) => s.toLowerCase().includes(k.toLowerCase())))
  );

  // Extract candidate's star projects or use rich defaults
  const featuredProjects: ResumeProject[] = candidate.githubMetrics?.featuredRepos?.length > 0
    ? candidate.githubMetrics.featuredRepos.map((r) => ({
        title: r.repoName,
        technologies: `${r.primaryLanguage}, Distributed Architecture, CI/CD`,
        bullets: [
          `Architected and shipped ${r.repoName} with high-availability clustering, reducing I/O latency by 35%.`,
          `Implemented automated testing pipelines and zero-downtime deployment workflows with ${r.primaryLanguage} and Docker.`,
          `Grew open-source adoption to ${r.stars} GitHub stars and active developer community contributions.`,
        ],
        githubUrl: `https://github.com/${candidate.githubMetrics.username || 'developer'}/${r.repoName}`,
      }))
    : [
        {
          title: 'OmniApply Autonomous Career Engine',
          technologies: 'React 18, TypeScript, Node.js, Express, Gemini 2.5 Flash, TailwindCSS',
          bullets: [
            'Engineered full-stack multi-platform job application synthesizer generating tailored ATS packages with sub-second response times.',
            'Integrated Gemini 2.5 Flash API with streaming telemetry, structured JSON schemas, and deterministic fallback heuristics.',
            'Implemented simulated Celery worker task queues and Redis cache monitoring with responsive UI instrumentation.',
          ],
        },
        {
          title: 'Distributed In-Memory Key-Value Store',
          technologies: 'Go, Raft Consensus, gRPC, Protobuf, LevelDB',
          bullets: [
            'Developed distributed storage node with write-ahead logging (WAL) and consistent hashing supporting 85k ops/sec.',
            'Engineered leader election and log replication algorithms adhering to Raft consensus with automated failover in <150ms.',
          ],
        },
      ];

  const structuredResume: ResumeData = {
    fullName: candidate.fullName || 'Shivam Singh',
    email: 'singhshivam20009@gmail.com',
    phone: '+91 98765 43210',
    location: 'Bangalore, India',
    links: {
      github: `github.com/${candidate.githubMetrics?.username || 'singhshivam'}`,
      linkedin: 'linkedin.com/in/shivam-singh',
      portfolio: 'shivamsingh.dev',
      leetcode: `leetcode.com/u/${candidate.leetcodeMetrics ? 'singhshivam' : 'profile'}`,
    },
    summary: candidate.executiveSummary || `Full-Stack Software Engineer with proven expertise in building scalable distributed systems, modern React frontends, and AI agent architectures.`,
    education: [
      {
        institution: 'National Institute of Technology (NIT)',
        degree: 'Bachelor of Technology in Computer Science & Engineering',
        location: 'India',
        duration: '2020 -- 2024',
        details: 'Relevant Coursework: Data Structures & Algorithms, Operating Systems, Distributed Systems, Database Management.',
      },
    ],
    skills: {
      languages: candidate.githubMetrics?.topLanguages?.length > 0 
        ? candidate.githubMetrics.topLanguages 
        : ['TypeScript', 'JavaScript', 'Python', 'Go', 'SQL', 'C++'],
      frameworks: ['React 18', 'Next.js', 'Node.js', 'Express', 'TailwindCSS', 'Redux / Zustand'],
      developerTools: ['Git', 'Docker', 'Kubernetes', 'Linux', 'Vite', 'Postman', 'Webpack'],
      librariesOrDatabases: ['PostgreSQL', 'Redis', 'MongoDB', 'GraphQL', 'Prisma / Drizzle ORM', 'gRPC'],
    },
    experience: [
      {
        role: `Software Engineer (${jobTitle.includes('Senior') ? 'Senior Core Engine' : 'Full-Stack & Systems'})`,
        company: 'Apex Cloud Solutions',
        location: 'Bangalore, India',
        duration: 'June 2024 -- Present',
        bullets: [
          `Spearheaded the development of real-time event streaming pipelines handling 10M+ daily events using Node.js and Redis.`,
          `Accelerated frontend dashboard rendering speed by 42% through React memoization, code-splitting, and virtualized lists.`,
          `Designed resilient REST and GraphQL APIs adhering to strict OpenAPI schemas with 99.98% uptime SLA.`,
          `Collaborated in Agile sprints with cross-functional design and product engineering teams, delivering 6 major production releases.`,
        ],
      },
      {
        role: 'Software Engineering Intern',
        company: 'NovaScale Technologies',
        location: 'Remote',
        duration: 'Jan 2024 -- May 2024',
        bullets: [
          `Engineered microservices in TypeScript and Express, optimizing PostgreSQL database query indexes to reduce P95 latency by 60ms.`,
          `Integrated automated CI/CD GitHub Actions workflows reducing deployment cycle duration from 25 minutes to 7 minutes.`,
          `Authored comprehensive technical documentation and unit test suites achieving 88% branch test coverage.`,
        ],
      },
    ],
    projects: featuredProjects,
  };

  const latexSource = buildLatexResumeDocument(structuredResume);

  return {
    latexSource,
    structuredResume,
    atsKeywordsTargeted: atsKeywordsTargeted.length > 0 ? atsKeywordsTargeted : ['TypeScript', 'React', 'Node.js', 'System Design', 'PostgreSQL', 'Docker'],
    tailoredForRole: jobTitle,
    tailoredForCompany: companyName,
  };
}
